// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PeoplesInfo.Models
{
    public partial class DTOState
    {
        public DTOState()
        {
            Cities = new HashSet<DTOCity>();
        }

        public int StateId { get; set; }
        public string StateName { get; set; }
        public int? CountryId { get; set; }

        public virtual DTOCountry Country { get; set; }
        public virtual ICollection<DTOCity> Cities { get; set; }
    }
}