// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace infoapi.Entities
{
    public partial class RoleTable
    {
        public RoleTable()
        {
            Sessions = new HashSet<Session>();
        }

        public int Id { get; set; }
        public string Role { get; set; }

        public virtual ICollection<Session> Sessions { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}