// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace infoapi.Entities
{
    public partial class Session
    {
        public int Id { get; set; }
        public int? UserId { get; set; }
        public int? RoleId { get; set; }
        public Guid SessionId { get; set; }
        public bool IsActive { get; set; }
        public DateTime LoginTime { get; set; }
        public DateTime? LogoutTime { get; set; }

        public virtual RoleTable Role { get; set; }
        public virtual User User { get; set; }
    }
}