// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Data;

namespace infoapi.Entities
{
    public partial class User
    {
        public User()
        {
            Sessions = new HashSet<Session>();
        }

        public int Id { get; set; }
        public string Username { get; set; }
        public string HashedPassword { get; set; }
        public string Salt { get; set; }
        public string EmailId { get; set; }

        public virtual ICollection<Session> Sessions { get; set; }
        public virtual ICollection<OTPTable> OTPs { get; set; }

        public int RoleId { get; set; }
        public RoleTable Role { get; set; }
    }
}