// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using PeoplesInfo.Models;

namespace PeoplesInfo
{
    public partial class infoContext : DbContext
    {
        public infoContext()
        {
        }

        public infoContext(DbContextOptions<infoContext> options)
            : base(options)
        {
        }

        public virtual DbSet<DTOCity> Cities { get; set; }
        public virtual DbSet<DTOCountry> Countries { get; set; }
        public virtual DbSet<DTOState> States { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {

                
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<DTOCity>(entity =>
            {
                entity.HasKey(e => e.CityId);
                entity.Property(e => e.CityName).HasMaxLength(100);

                entity.HasOne(d => d.State)
                    .WithMany(p => p.Cities)
                    .HasForeignKey(d => d.StateId)
                    .HasConstraintName("FK__Cities__StateId__3B75D760");
            });

            modelBuilder.Entity<DTOCountry>(entity =>
            {   entity.HasKey(e => e.CountryId);
                entity.Property(e => e.CountryName).HasMaxLength(100);
            });

            modelBuilder.Entity<DTOState>(entity =>
            {
                entity.HasKey(e => e.CountryId);
                entity.Property(e => e.StateName).HasMaxLength(100);

                entity.HasOne(d => d.Country)
                    .WithMany(p => p.States)
                    .HasForeignKey(d => d.CountryId)
                    .HasConstraintName("FK__States__CountryI__38996AB5");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}